-- failed ASTNodeDefs.py: Traceback (most recent call last):
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 135, in process_file
    ok, msg = process_file(p, out_root)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 101, in process_file
    rel = path.relative_to(DOWNLOADS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\anaconda3\Lib\pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'C:\\Users\\andy\\AppData\\Local\\Temp\\tmp4b13710z\\CMPSC_461_Project1\\ASTNodeDefs.py' is not in the subpath of 'C:\\Users\\andy\\Videos\\hackpsu_fa25\\downloads'

-- failed checker.py: Traceback (most recent call last):
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 135, in process_file
    ok, msg = process_file(p, out_root)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 101, in process_file
    rel = path.relative_to(DOWNLOADS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\anaconda3\Lib\pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'C:\\Users\\andy\\AppData\\Local\\Temp\\tmp4b13710z\\CMPSC_461_Project1\\checker.py' is not in the subpath of 'C:\\Users\\andy\\Videos\\hackpsu_fa25\\downloads'

-- failed grammar.txt: Traceback (most recent call last):
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 135, in process_file
    ok, msg = process_file(p, out_root)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 101, in process_file
    rel = path.relative_to(DOWNLOADS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\anaconda3\Lib\pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'C:\\Users\\andy\\AppData\\Local\\Temp\\tmp4b13710z\\CMPSC_461_Project1\\grammar.txt' is not in the subpath of 'C:\\Users\\andy\\Videos\\hackpsu_fa25\\downloads'

-- failed Parser.py: Traceback (most recent call last):
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 135, in process_file
    ok, msg = process_file(p, out_root)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 101, in process_file
    rel = path.relative_to(DOWNLOADS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\anaconda3\Lib\pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'C:\\Users\\andy\\AppData\\Local\\Temp\\tmp4b13710z\\CMPSC_461_Project1\\Parser.py' is not in the subpath of 'C:\\Users\\andy\\Videos\\hackpsu_fa25\\downloads'

-- failed tokens.txt: Traceback (most recent call last):
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 135, in process_file
    ok, msg = process_file(p, out_root)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 101, in process_file
    rel = path.relative_to(DOWNLOADS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\anaconda3\Lib\pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'C:\\Users\\andy\\AppData\\Local\\Temp\\tmp4b13710z\\CMPSC_461_Project1\\tokens.txt' is not in the subpath of 'C:\\Users\\andy\\Videos\\hackpsu_fa25\\downloads'

-- failed verify.py: Traceback (most recent call last):
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 135, in process_file
    ok, msg = process_file(p, out_root)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\andy\Videos\hackpsu_fa25\scripts\extract_text_from_downloads.py", line 101, in process_file
    rel = path.relative_to(DOWNLOADS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\anaconda3\Lib\pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'C:\\Users\\andy\\AppData\\Local\\Temp\\tmp4b13710z\\CMPSC_461_Project1\\verify.py' is not in the subpath of 'C:\\Users\\andy\\Videos\\hackpsu_fa25\\downloads'
